name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-docker:
    runs-on: ubuntu-latest
    env:
      CI_REGISTRY_IMAGE: *****.dkr.ecr.eu-west-1.amazonaws.com/****
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv install --dev

      - name: Build Docker image
        run: |
          mkdir -p /kaniko/.docker
          echo $CI_REGISTRY_IMAGE
          echo $GITHUB_REF
          echo $GITHUB_SHA
          echo "{\"credsStore\":\"ecr-login\"}" > /kaniko/.docker/config.json
          if [[ -n "$GITHUB_REF" && "$GITHUB_REF" != "refs/heads/main" ]]; then
            TAG=$(echo $GITHUB_REF | sed 's/refs\/heads\///')
          elif [[ -n "$GITHUB_REF" && "$GITHUB_REF" == "refs/heads/main" ]]; then
            TAG="latest"
          elif [[ -n "$GITHUB_REF" && "$GITHUB_REF" =~ "refs/tags/" ]]; then
            TAG=$(echo $GITHUB_REF | sed 's/refs\/tags\///')
          fi
          /kaniko/executor --context $GITHUB_WORKSPACE --dockerfile $GITHUB_WORKSPACE/Dockerfile --destination $CI_REGISTRY_IMAGE:$TAG --build-arg=CI_DEPLOY_USER --build-arg=CI_DEPLOY_PASSWORD

      - name: Push Docker image
        run: docker push $CI_REGISTRY_IMAGE:$TAG

    if: github.event_name == 'push' && github.ref == 'refs/heads/main' || github.event_name == 'pull_request'

  compute:
    needs: build-docker
    runs-on: ubuntu-latest
    env:
      MLFLOW_TRACKING_URI:
      MLFLOW_TRACKING_USERNAME: 
      MLFLOW_TRACKING_PASSWORD:
      PYCARET_CUSTOM_LOGGING_LEVEL: CRITICAL
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8

      - name: Run App
        run: |
          cd /project
          pipenv run python main_scriipt.py

    if: github.event_name == 'push' && github.ref == 'refs/heads/main' || github.event_name == 'pull_request'
